image: alpine:latest

pages:
  stage: deploy
  script:
    - echo 'Nothing to do...'
  artifacts:
    paths:
      - public/
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      changes:
        - public/*
      when: always
